LicenseManager/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using IntraLicenseLibrary;
using LicenseManager.Infrastructure.Attributes;
using LicenseManager.Models.ViewModels;
using LicenseManager.Services.Interfaces;
using Microsoft.Web.Mvc;

namespace LicenseManager.Controllers
{
    public class LicenseController : AppController
    {
        public List<INewLicenseViewModel> NewLicenseSteps { get; protected set; }
        public ICacheService CacheService { get; protected set; }

        public LicenseController(List<INewLicenseViewModel> newLicenseSteps, ICacheService cacheService)
        {
            NewLicenseSteps = newLicenseSteps;
            CacheService = cacheService;
        }

        [IntraRoute("license/new", Name = RouteNames.LicenseNew)]
        public ActionResult New()
        {
            var licenseWizard = new NewLicenseViewModel(NewLicenseSteps);
            return View(licenseWizard);
        }

        [IntraRoute("license/create", HttpVerbs.Post, Name = RouteNames.LicenseNextStep)]
        public ActionResult NextStep([Deserialize] NewLicenseViewModel licenseWizard, INewLicenseViewModel step)
        {
            licenseWizard.Steps[licenseWizard.CurrentStepIndex] = step;
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(Request["next"]))
                {
                    licenseWizard.CurrentStepIndex++;
                }
                else if (!string.IsNullOrEmpty(Request["prev"]))
                {
                    licenseWizard.CurrentStepIndex--;
                }
                else
                {
                    // TODO: we have finished: all the step partial
                    // view models have passed validation => map them
                    // back to the domain model and do some processing with
                    // the results

                    return Content("thanks for filling this form", "text/plain");
                }
            }
            else if (!string.IsNullOrEmpty(Request["prev"]))
            {
                // Even if validation failed we allow the user to navigate to previous steps
                licenseWizard.CurrentStepIndex--;
            }

            return View("New", licenseWizard);
        }
    }
}

LicenseManager/Views/License/New.cshtml
@model LicenseManager.Models.ViewModels.NewLicenseViewModel

@{
    Layout = "../Shared/_FocusedLayout.cshtml";
    ViewBag.Title = "New License - LM";
    var currentStep = Model.Steps[Model.CurrentStepIndex];
}

<h2>Create a new license</h2>
@using (Html.BeginForm("NextStep", "License", FormMethod.Post, new { @class = "aui" }))
{
    @Html.AntiForgeryToken()
    
    @Html.Hidden("licenseWizard", new Microsoft.Web.Mvc.MvcSerializer().Serialize(Model))
    @Html.Hidden("StepType", currentStep.GetType())
    
    if (Model.CurrentStepIndex > 0) { }
    
    @Html.EditorFor(x => currentStep, null, "")

    <div class="buttons-container">
        <div class="buttons">
            @if (Model.CurrentStepIndex < Model.Steps.Count - 1)
            {
                <input class="aui-button aui-button-primary" type="submit" id="next" name="next" value="Next">
            }
            else
            {
                <input class="aui-button aui-button-primary" type="submit" id="submit" name="submit" value="Create license">
            }

            @if (Model.CurrentStepIndex > 0)
            {
                <input class="aui-button aui-button-link" type="submit" id="prev" name="prev" value="Previous">
@*                <a id="prev" class="aui-button aui-button-link" name="prev" accesskey="c" href="#">Previous</a>*@
            }
            else
            {
                <a id="cancel" class="aui-button aui-button-link" name="cancel" accesskey="c" href="#">Cancel</a>
            }
        </div>
    </div>
}

@section secondaryScripts
{
    <script type="text/javascript">
        AJS.$('select').auiSelect2();
    </script>
}